### ISSUE TITLE
Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future

### ISSUE THREAD

**Issue by DavidGodefroid** [nayzo/elastic-query-bundle#9]
There is a depreciation here: https://github.com/nayzo/NzoElasticQueryBundle/blob/master/DependencyInjection/Configuration.php

**Comment by nayzo** [comment]
Hello,
What Symfony version are you using ?

**Comment by DavidGodefroid** [comment]
Hi, 

5.4, released yesterday 😉

**Comment by nayzo** [comment]
it should be good now,
cf: https://github.com/nayzo/NzoElasticQueryBundle/releases/tag/v3.1.1
